### ISSUE TITLE
Content served over http

### ISSUE THREAD

**Issue by foffer** [diegoddox/react-redux-toastr#27]
Serving your site from a https source produces the following error: 
`Mixed Content: The page at 'https://xx.xx.com/login' was loaded over HTTPS, but requested an insecure font 'http://diegoddox.github.io/react-redux-toastr/fonts/redux-toastr.woff'. This request has been blocked; the content must be served over HTTPS.`

**Comment by diegoddox** [comment]
Can u update to the lasted.

**Comment by diegoddox** [comment]
@foffer 
I will close the issue as I have put the icons in the `lib` folder and this should fix the problem, but feel free to re-open in case you got stuck.

**Comment by foffer** [comment]
@diegoddox sorry for my lack in response. The update fixed the issue!

**Comment by diegoddox** [comment]
@foffer np, you're welcome.

**Comment by febeck** [comment]
@diegoddox , I still have the same issue with project's css...

`Mixed Content: The page at 'https://xxxxxxx.com/login' was loaded over HTTPS, but requested an insecure stylesheet 'http://diegoddox.github.io/react-redux-toastr/7.1/react-redux-toastr.min.css'. This request has been blocked; the content must be served over HTTPS.`

**Comment by diegoddox** [comment]
Apologize me @febeck but at the moment I think there are only two things you can do

1. import the style to your `react-application` and buddle it together
2. copy the entire `CSS` file and add to your server

**Comment by febeck** [comment]
@diegoddox , thank you for your answer and sorry for the delay. Actually there is another way to solve this problem. I don't know if you were aware, but GitHub pages [have enabled https](https://github.com/blog/2186-https-for-github-pages) and therefore you can get the css via the `<link>` tag. So why not update the project README and also demo page to use it ?

**Comment by diegoddox** [comment]
Thank you so much for the info @febeck, I will take a look.

**Comment by diegoddox** [comment]
[Fixed](https://diegoddox.github.io/react-redux-toastr/7.1/react-redux-toastr.min.css)
